export const COMPANY_DEFAULT_PERMISSIONS = {
    // ── Master Group ──
    user: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    role: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    location: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    employee: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },

    // ── Root Group (Super Admin only - disabled for Company Admin) ──
    tools: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    company: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    subscription: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    plans: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    payments: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    discount: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },

    // ── Company-level modules ──
    payment: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    report: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    assessment: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    settings: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },

    // ── HRM Modules (full access for all locations) ──
    holiday_calendar: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    document: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    contract: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    leave: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    attendance: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    shift: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    compliance: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },

    // ── Catalogue Modules (full access) ──
    categories: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    uom: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    countries: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    states: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    cities: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    "port-master": {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    reports: {
        // Read-only module — aggregation reports have no write endpoints.
        can_all: false,
        can_read: true,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    invoices: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    shipping: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    products: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    vendors: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    customers: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    leads: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    rebates: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    expenses: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    currencies: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    "price-list": {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },

    // ── Sales Group (Quotation → PFI → Purchase Order) ──
    quotations: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    rfq: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    pfi: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    "purchase-orders": {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    "po-vendors": {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    tracking: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_delete: true,
    },
    inventory: {
        can_all: true,
        can_read: true,
    },
} as const;

export type CompanyPermissions = typeof COMPANY_DEFAULT_PERMISSIONS;
