export const COMPANY_DEFAULT_PERMISSIONS = {
    // ── Master Group ──
    user: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    role: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    location: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    employee: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },

    // ── Root Group (Super Admin only — disabled for Company Admin) ──
    tools: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    company: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    subscription: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    plans: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    payments: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    discount: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },

    // ── Company-level modules ──
    payment: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    report: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    assessment: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    settings: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },

    // ── HRM Modules (full access for all locations) ──
    holiday_calendar: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    document: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    contract: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    leave: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    attendance: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    shift: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    compliance: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
} as const;

export type CompanyPermissions = typeof COMPANY_DEFAULT_PERMISSIONS;
