export const LOCATION_ADMIN_DEFAULT_PERMISSIONS = {
    // ── Master Group (can manage users, roles, employees — NOT locations) ──
    user: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    role: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    location: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    employee: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },

    // ── Root Group (Super Admin only — disabled for Location Admin) ──
    tools: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    company: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    subscription: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    plans: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    payments: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    discount: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },

    // ── Company-level modules (limited for location scope) ──
    payment: {
        can_all: false,
        can_read: true,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    report: {
        can_all: false,
        can_read: true,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    assessment: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    settings: {
        can_all: false,
        can_read: true,
        can_add: false,
        can_create: false,
        can_update: true,
        can_delete: false,
    },

    // ── HRM Modules (full access — scoped to own location by backend) ──
    holiday_calendar: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    document: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    contract: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    leave: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    attendance: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    shift: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },
    compliance: {
        can_all: true,
        can_read: true,
        can_add: true,
        can_create: true,
        can_update: true,
        can_delete: true,
    },

    // ── Catalogue Modules (read-only — cannot manage per spec) ──
    categories: {
        can_all: false,
        can_read: true,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    products: {
        can_all: false,
        can_read: true,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    vendors: {
        can_all: false,
        can_read: true,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    customers: {
        can_all: false,
        can_read: true,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
    currencies: {
        can_all: false,
        can_read: true,
        can_add: false,
        can_create: false,
        can_update: false,
        can_delete: false,
    },
} as const;

export type LocationAdminPermissions = typeof LOCATION_ADMIN_DEFAULT_PERMISSIONS;
