export const SYSTEM_USER_DEFAULT_PERMISSIONS = {
    user: {
        can_all: false,
        can_read: true,
        can_add: false,
        can_update: false,
        can_delete: false,
    },
    role: {
        can_all: false,
        can_read: true,
        can_add: false,
        can_update: false,
        can_delete: false,
    },
    tools: {
        can_all: false,
        can_read: true,
        can_add: false,
        can_update: false,
        can_delete: false,
    },
    company: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_update: false,
        can_delete: false,
    },
    plans: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_update: false,
        can_delete: false,
    },
    subscription: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_update: false,
        can_delete: false,
    },
    payments: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_update: false,
        can_delete: false,
    },
    discount: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_update: false,
        can_delete: false,
    },
    agent: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_update: false,
        can_delete: false,
    },
    event_log: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_update: false,
        can_delete: false,
    },
    assessment: {
        can_all: false,
        can_read: false,
        can_add: false,
        can_update: false,
        can_delete: false,
    },
} as const;

export type SystemUsersPermissions = typeof SYSTEM_USER_DEFAULT_PERMISSIONS;
