export enum ENUM_USER_SIGN_UP_FROM {
    ADMIN = 'ADMIN',
    PUBLIC = 'PUBLIC',
    SEED = 'SEED',
}

export enum ENUM_USER_STATUS {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    BLOCKED = 'BLOCKED',
}

export enum ENUM_USER_GENDER {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
}

export enum ENUM_USER_INACTIVE_REASON {
    MANUAL = 'MANUAL',
    SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
    COMPANY_SUSPENDED = 'COMPANY_SUSPENDED',
}
