export enum ENUM_ASSESSMENT_STATUS_CODE_ERROR {
    ASSESSMENT_NOT_FOUND_ERROR = 5300,
    ASSESSMENT_EXISTS_ERROR = 5301,
    ASSESSMENT_USED_ERROR = 5302,
    
    ASSESSMENT_REPORT_NOT_FOUND_ERROR = 5310,
    ASSESSMENT_REPORT_EXISTS_ERROR = 5311,
    
    SECTION_NOT_FOUND_ERROR = 5320,
    SECTION_EXISTS_ERROR = 5321,
    
    QUESTION_NOT_FOUND_ERROR = 5330,
    QUESTION_EXISTS_ERROR = 5331,
    
    QUESTION_ANSWER_NOT_FOUND_ERROR = 5340,
    QUESTION_ANSWER_EXISTS_ERROR = 5341,
}