export enum ENUM_UNIFIED_AUTH_STATUS_CODE_ERROR {
    SHARED_USER_NOT_FOUND = 5001,
    SHARED_USER_INVALID_CREDENTIALS = 5002,
    INVALID_USER_TYPE = 5003,
    TENANT_USER_DATA_NOT_FOUND = 5004,
    TENANT_DATABASE_UNAVAILABLE = 5005,
    TENANT_CONNECTION_FAILED = 5006,
    MIGRATION_FAILED = 5007,
    SHARED_USER_CREATION_FAILED = 5008,
    SHARED_USER_UPDATE_FAILED = 5009,
    DATA_INCONSISTENCY = 5010,
    TENANT_ROLE_NOT_FOUND = 5011,
    COMPANY_DATA_NOT_FOUND = 5012,
}