import { ICountrySeedRow } from '@modules/country/interfaces/country.seed.interface';

/**
 * ISO 3166-1 country list, generated from the `world-countries` dataset the
 * frontend already ships (`getCountryList()` in countryTimezoneUtils.js). Same
 * source, so the codes this master stores are the codes existing records hold.
 *
 * Seeded on boot, only when the table is empty — see CountrySeedService.
 * `currency_code` is the primary currency; `time_zone` the primary IANA zone.
 */
export const COUNTRIES_SEED: ICountrySeedRow[] = [
    { name: "Afghanistan", country_code: "AF", currency_code: "AFN", time_zone: "" },
    { name: "Åland Islands", country_code: "AX", currency_code: "EUR", time_zone: "" },
    { name: "Albania", country_code: "AL", currency_code: "ALL", time_zone: "" },
    { name: "Algeria", country_code: "DZ", currency_code: "DZD", time_zone: "" },
    { name: "American Samoa", country_code: "AS", currency_code: "USD", time_zone: "" },
    { name: "Andorra", country_code: "AD", currency_code: "EUR", time_zone: "" },
    { name: "Angola", country_code: "AO", currency_code: "AOA", time_zone: "" },
    { name: "Anguilla", country_code: "AI", currency_code: "XCD", time_zone: "" },
    { name: "Antarctica", country_code: "AQ", currency_code: "", time_zone: "" },
    { name: "Antigua and Barbuda", country_code: "AG", currency_code: "XCD", time_zone: "" },
    { name: "Argentina", country_code: "AR", currency_code: "ARS", time_zone: "" },
    { name: "Armenia", country_code: "AM", currency_code: "AMD", time_zone: "" },
    { name: "Aruba", country_code: "AW", currency_code: "AWG", time_zone: "" },
    { name: "Australia", country_code: "AU", currency_code: "AUD", time_zone: "" },
    { name: "Austria", country_code: "AT", currency_code: "EUR", time_zone: "" },
    { name: "Azerbaijan", country_code: "AZ", currency_code: "AZN", time_zone: "" },
    { name: "Bahamas", country_code: "BS", currency_code: "BSD", time_zone: "" },
    { name: "Bahrain", country_code: "BH", currency_code: "BHD", time_zone: "" },
    { name: "Bangladesh", country_code: "BD", currency_code: "BDT", time_zone: "" },
    { name: "Barbados", country_code: "BB", currency_code: "BBD", time_zone: "" },
    { name: "Belarus", country_code: "BY", currency_code: "BYN", time_zone: "" },
    { name: "Belgium", country_code: "BE", currency_code: "EUR", time_zone: "" },
    { name: "Belize", country_code: "BZ", currency_code: "BZD", time_zone: "" },
    { name: "Benin", country_code: "BJ", currency_code: "XOF", time_zone: "" },
    { name: "Bermuda", country_code: "BM", currency_code: "BMD", time_zone: "" },
    { name: "Bhutan", country_code: "BT", currency_code: "BTN", time_zone: "" },
    { name: "Bolivia", country_code: "BO", currency_code: "BOB", time_zone: "" },
    { name: "Bosnia and Herzegovina", country_code: "BA", currency_code: "BAM", time_zone: "" },
    { name: "Botswana", country_code: "BW", currency_code: "BWP", time_zone: "" },
    { name: "Bouvet Island", country_code: "BV", currency_code: "", time_zone: "" },
    { name: "Brazil", country_code: "BR", currency_code: "BRL", time_zone: "" },
    { name: "British Indian Ocean Territory", country_code: "IO", currency_code: "USD", time_zone: "" },
    { name: "British Virgin Islands", country_code: "VG", currency_code: "USD", time_zone: "" },
    { name: "Brunei", country_code: "BN", currency_code: "BND", time_zone: "" },
    { name: "Bulgaria", country_code: "BG", currency_code: "BGN", time_zone: "" },
    { name: "Burkina Faso", country_code: "BF", currency_code: "XOF", time_zone: "" },
    { name: "Burundi", country_code: "BI", currency_code: "BIF", time_zone: "" },
    { name: "Cambodia", country_code: "KH", currency_code: "KHR", time_zone: "" },
    { name: "Cameroon", country_code: "CM", currency_code: "XAF", time_zone: "" },
    { name: "Canada", country_code: "CA", currency_code: "CAD", time_zone: "" },
    { name: "Cape Verde", country_code: "CV", currency_code: "CVE", time_zone: "" },
    { name: "Caribbean Netherlands", country_code: "BQ", currency_code: "USD", time_zone: "" },
    { name: "Cayman Islands", country_code: "KY", currency_code: "KYD", time_zone: "" },
    { name: "Central African Republic", country_code: "CF", currency_code: "XAF", time_zone: "" },
    { name: "Chad", country_code: "TD", currency_code: "XAF", time_zone: "" },
    { name: "Chile", country_code: "CL", currency_code: "CLP", time_zone: "" },
    { name: "China", country_code: "CN", currency_code: "CNY", time_zone: "" },
    { name: "Christmas Island", country_code: "CX", currency_code: "AUD", time_zone: "" },
    { name: "Cocos (Keeling) Islands", country_code: "CC", currency_code: "AUD", time_zone: "" },
    { name: "Colombia", country_code: "CO", currency_code: "COP", time_zone: "" },
    { name: "Comoros", country_code: "KM", currency_code: "KMF", time_zone: "" },
    { name: "Cook Islands", country_code: "CK", currency_code: "CKD", time_zone: "" },
    { name: "Costa Rica", country_code: "CR", currency_code: "CRC", time_zone: "" },
    { name: "Croatia", country_code: "HR", currency_code: "EUR", time_zone: "" },
    { name: "Cuba", country_code: "CU", currency_code: "CUC", time_zone: "" },
    { name: "Curaçao", country_code: "CW", currency_code: "ANG", time_zone: "" },
    { name: "Cyprus", country_code: "CY", currency_code: "EUR", time_zone: "" },
    { name: "Czechia", country_code: "CZ", currency_code: "CZK", time_zone: "" },
    { name: "Denmark", country_code: "DK", currency_code: "DKK", time_zone: "" },
    { name: "Djibouti", country_code: "DJ", currency_code: "DJF", time_zone: "" },
    { name: "Dominica", country_code: "DM", currency_code: "XCD", time_zone: "" },
    { name: "Dominican Republic", country_code: "DO", currency_code: "DOP", time_zone: "" },
    { name: "DR Congo", country_code: "CD", currency_code: "CDF", time_zone: "" },
    { name: "Ecuador", country_code: "EC", currency_code: "USD", time_zone: "" },
    { name: "Egypt", country_code: "EG", currency_code: "EGP", time_zone: "" },
    { name: "El Salvador", country_code: "SV", currency_code: "USD", time_zone: "" },
    { name: "Equatorial Guinea", country_code: "GQ", currency_code: "XAF", time_zone: "" },
    { name: "Eritrea", country_code: "ER", currency_code: "ERN", time_zone: "" },
    { name: "Estonia", country_code: "EE", currency_code: "EUR", time_zone: "" },
    { name: "Eswatini", country_code: "SZ", currency_code: "SZL", time_zone: "" },
    { name: "Ethiopia", country_code: "ET", currency_code: "ETB", time_zone: "" },
    { name: "Falkland Islands", country_code: "FK", currency_code: "FKP", time_zone: "" },
    { name: "Faroe Islands", country_code: "FO", currency_code: "DKK", time_zone: "" },
    { name: "Fiji", country_code: "FJ", currency_code: "FJD", time_zone: "" },
    { name: "Finland", country_code: "FI", currency_code: "EUR", time_zone: "" },
    { name: "France", country_code: "FR", currency_code: "EUR", time_zone: "" },
    { name: "French Guiana", country_code: "GF", currency_code: "EUR", time_zone: "" },
    { name: "French Polynesia", country_code: "PF", currency_code: "XPF", time_zone: "" },
    { name: "French Southern and Antarctic Lands", country_code: "TF", currency_code: "EUR", time_zone: "" },
    { name: "Gabon", country_code: "GA", currency_code: "XAF", time_zone: "" },
    { name: "Gambia", country_code: "GM", currency_code: "GMD", time_zone: "" },
    { name: "Georgia", country_code: "GE", currency_code: "GEL", time_zone: "" },
    { name: "Germany", country_code: "DE", currency_code: "EUR", time_zone: "" },
    { name: "Ghana", country_code: "GH", currency_code: "GHS", time_zone: "" },
    { name: "Gibraltar", country_code: "GI", currency_code: "GIP", time_zone: "" },
    { name: "Greece", country_code: "GR", currency_code: "EUR", time_zone: "" },
    { name: "Greenland", country_code: "GL", currency_code: "DKK", time_zone: "" },
    { name: "Grenada", country_code: "GD", currency_code: "XCD", time_zone: "" },
    { name: "Guadeloupe", country_code: "GP", currency_code: "EUR", time_zone: "" },
    { name: "Guam", country_code: "GU", currency_code: "USD", time_zone: "" },
    { name: "Guatemala", country_code: "GT", currency_code: "GTQ", time_zone: "" },
    { name: "Guernsey", country_code: "GG", currency_code: "GBP", time_zone: "" },
    { name: "Guinea", country_code: "GN", currency_code: "GNF", time_zone: "" },
    { name: "Guinea-Bissau", country_code: "GW", currency_code: "XOF", time_zone: "" },
    { name: "Guyana", country_code: "GY", currency_code: "GYD", time_zone: "" },
    { name: "Haiti", country_code: "HT", currency_code: "HTG", time_zone: "" },
    { name: "Heard Island and McDonald Islands", country_code: "HM", currency_code: "", time_zone: "" },
    { name: "Honduras", country_code: "HN", currency_code: "HNL", time_zone: "" },
    { name: "Hong Kong", country_code: "HK", currency_code: "HKD", time_zone: "" },
    { name: "Hungary", country_code: "HU", currency_code: "HUF", time_zone: "" },
    { name: "Iceland", country_code: "IS", currency_code: "ISK", time_zone: "" },
    { name: "India", country_code: "IN", currency_code: "INR", time_zone: "" },
    { name: "Indonesia", country_code: "ID", currency_code: "IDR", time_zone: "" },
    { name: "Iran", country_code: "IR", currency_code: "IRR", time_zone: "" },
    { name: "Iraq", country_code: "IQ", currency_code: "IQD", time_zone: "" },
    { name: "Ireland", country_code: "IE", currency_code: "EUR", time_zone: "" },
    { name: "Isle of Man", country_code: "IM", currency_code: "GBP", time_zone: "" },
    { name: "Israel", country_code: "IL", currency_code: "ILS", time_zone: "" },
    { name: "Italy", country_code: "IT", currency_code: "EUR", time_zone: "" },
    { name: "Ivory Coast", country_code: "CI", currency_code: "XOF", time_zone: "" },
    { name: "Jamaica", country_code: "JM", currency_code: "JMD", time_zone: "" },
    { name: "Japan", country_code: "JP", currency_code: "JPY", time_zone: "" },
    { name: "Jersey", country_code: "JE", currency_code: "GBP", time_zone: "" },
    { name: "Jordan", country_code: "JO", currency_code: "JOD", time_zone: "" },
    { name: "Kazakhstan", country_code: "KZ", currency_code: "KZT", time_zone: "" },
    { name: "Kenya", country_code: "KE", currency_code: "KES", time_zone: "" },
    { name: "Kiribati", country_code: "KI", currency_code: "AUD", time_zone: "" },
    { name: "Kosovo", country_code: "XK", currency_code: "EUR", time_zone: "" },
    { name: "Kuwait", country_code: "KW", currency_code: "KWD", time_zone: "" },
    { name: "Kyrgyzstan", country_code: "KG", currency_code: "KGS", time_zone: "" },
    { name: "Laos", country_code: "LA", currency_code: "LAK", time_zone: "" },
    { name: "Latvia", country_code: "LV", currency_code: "EUR", time_zone: "" },
    { name: "Lebanon", country_code: "LB", currency_code: "LBP", time_zone: "" },
    { name: "Lesotho", country_code: "LS", currency_code: "LSL", time_zone: "" },
    { name: "Liberia", country_code: "LR", currency_code: "LRD", time_zone: "" },
    { name: "Libya", country_code: "LY", currency_code: "LYD", time_zone: "" },
    { name: "Liechtenstein", country_code: "LI", currency_code: "CHF", time_zone: "" },
    { name: "Lithuania", country_code: "LT", currency_code: "EUR", time_zone: "" },
    { name: "Luxembourg", country_code: "LU", currency_code: "EUR", time_zone: "" },
    { name: "Macau", country_code: "MO", currency_code: "MOP", time_zone: "" },
    { name: "Madagascar", country_code: "MG", currency_code: "MGA", time_zone: "" },
    { name: "Malawi", country_code: "MW", currency_code: "MWK", time_zone: "" },
    { name: "Malaysia", country_code: "MY", currency_code: "MYR", time_zone: "" },
    { name: "Maldives", country_code: "MV", currency_code: "MVR", time_zone: "" },
    { name: "Mali", country_code: "ML", currency_code: "XOF", time_zone: "" },
    { name: "Malta", country_code: "MT", currency_code: "EUR", time_zone: "" },
    { name: "Marshall Islands", country_code: "MH", currency_code: "USD", time_zone: "" },
    { name: "Martinique", country_code: "MQ", currency_code: "EUR", time_zone: "" },
    { name: "Mauritania", country_code: "MR", currency_code: "MRU", time_zone: "" },
    { name: "Mauritius", country_code: "MU", currency_code: "MUR", time_zone: "" },
    { name: "Mayotte", country_code: "YT", currency_code: "EUR", time_zone: "" },
    { name: "Mexico", country_code: "MX", currency_code: "MXN", time_zone: "" },
    { name: "Micronesia", country_code: "FM", currency_code: "", time_zone: "" },
    { name: "Moldova", country_code: "MD", currency_code: "MDL", time_zone: "" },
    { name: "Monaco", country_code: "MC", currency_code: "EUR", time_zone: "" },
    { name: "Mongolia", country_code: "MN", currency_code: "MNT", time_zone: "" },
    { name: "Montenegro", country_code: "ME", currency_code: "EUR", time_zone: "" },
    { name: "Montserrat", country_code: "MS", currency_code: "XCD", time_zone: "" },
    { name: "Morocco", country_code: "MA", currency_code: "MAD", time_zone: "" },
    { name: "Mozambique", country_code: "MZ", currency_code: "MZN", time_zone: "" },
    { name: "Myanmar", country_code: "MM", currency_code: "MMK", time_zone: "" },
    { name: "Namibia", country_code: "NA", currency_code: "NAD", time_zone: "" },
    { name: "Nauru", country_code: "NR", currency_code: "AUD", time_zone: "" },
    { name: "Nepal", country_code: "NP", currency_code: "NPR", time_zone: "" },
    { name: "Netherlands", country_code: "NL", currency_code: "EUR", time_zone: "" },
    { name: "New Caledonia", country_code: "NC", currency_code: "XPF", time_zone: "" },
    { name: "New Zealand", country_code: "NZ", currency_code: "NZD", time_zone: "" },
    { name: "Nicaragua", country_code: "NI", currency_code: "NIO", time_zone: "" },
    { name: "Niger", country_code: "NE", currency_code: "XOF", time_zone: "" },
    { name: "Nigeria", country_code: "NG", currency_code: "NGN", time_zone: "" },
    { name: "Niue", country_code: "NU", currency_code: "NZD", time_zone: "" },
    { name: "Norfolk Island", country_code: "NF", currency_code: "AUD", time_zone: "" },
    { name: "North Korea", country_code: "KP", currency_code: "KPW", time_zone: "" },
    { name: "North Macedonia", country_code: "MK", currency_code: "MKD", time_zone: "" },
    { name: "Northern Mariana Islands", country_code: "MP", currency_code: "USD", time_zone: "" },
    { name: "Norway", country_code: "NO", currency_code: "NOK", time_zone: "" },
    { name: "Oman", country_code: "OM", currency_code: "OMR", time_zone: "" },
    { name: "Pakistan", country_code: "PK", currency_code: "PKR", time_zone: "" },
    { name: "Palau", country_code: "PW", currency_code: "USD", time_zone: "" },
    { name: "Palestine", country_code: "PS", currency_code: "EGP", time_zone: "" },
    { name: "Panama", country_code: "PA", currency_code: "PAB", time_zone: "" },
    { name: "Papua New Guinea", country_code: "PG", currency_code: "PGK", time_zone: "" },
    { name: "Paraguay", country_code: "PY", currency_code: "PYG", time_zone: "" },
    { name: "Peru", country_code: "PE", currency_code: "PEN", time_zone: "" },
    { name: "Philippines", country_code: "PH", currency_code: "PHP", time_zone: "" },
    { name: "Pitcairn Islands", country_code: "PN", currency_code: "NZD", time_zone: "" },
    { name: "Poland", country_code: "PL", currency_code: "PLN", time_zone: "" },
    { name: "Portugal", country_code: "PT", currency_code: "EUR", time_zone: "" },
    { name: "Puerto Rico", country_code: "PR", currency_code: "USD", time_zone: "" },
    { name: "Qatar", country_code: "QA", currency_code: "QAR", time_zone: "" },
    { name: "Republic of the Congo", country_code: "CG", currency_code: "XAF", time_zone: "" },
    { name: "Réunion", country_code: "RE", currency_code: "EUR", time_zone: "" },
    { name: "Romania", country_code: "RO", currency_code: "RON", time_zone: "" },
    { name: "Russia", country_code: "RU", currency_code: "RUB", time_zone: "" },
    { name: "Rwanda", country_code: "RW", currency_code: "RWF", time_zone: "" },
    { name: "Saint Barthélemy", country_code: "BL", currency_code: "EUR", time_zone: "" },
    { name: "Saint Helena, Ascension and Tristan da Cunha", country_code: "SH", currency_code: "GBP", time_zone: "" },
    { name: "Saint Kitts and Nevis", country_code: "KN", currency_code: "XCD", time_zone: "" },
    { name: "Saint Lucia", country_code: "LC", currency_code: "XCD", time_zone: "" },
    { name: "Saint Martin", country_code: "MF", currency_code: "EUR", time_zone: "" },
    { name: "Saint Pierre and Miquelon", country_code: "PM", currency_code: "EUR", time_zone: "" },
    { name: "Saint Vincent and the Grenadines", country_code: "VC", currency_code: "XCD", time_zone: "" },
    { name: "Samoa", country_code: "WS", currency_code: "WST", time_zone: "" },
    { name: "San Marino", country_code: "SM", currency_code: "EUR", time_zone: "" },
    { name: "São Tomé and Príncipe", country_code: "ST", currency_code: "STN", time_zone: "" },
    { name: "Saudi Arabia", country_code: "SA", currency_code: "SAR", time_zone: "" },
    { name: "Senegal", country_code: "SN", currency_code: "XOF", time_zone: "" },
    { name: "Serbia", country_code: "RS", currency_code: "RSD", time_zone: "" },
    { name: "Seychelles", country_code: "SC", currency_code: "SCR", time_zone: "" },
    { name: "Sierra Leone", country_code: "SL", currency_code: "SLL", time_zone: "" },
    { name: "Singapore", country_code: "SG", currency_code: "SGD", time_zone: "" },
    { name: "Sint Maarten", country_code: "SX", currency_code: "ANG", time_zone: "" },
    { name: "Slovakia", country_code: "SK", currency_code: "EUR", time_zone: "" },
    { name: "Slovenia", country_code: "SI", currency_code: "EUR", time_zone: "" },
    { name: "Solomon Islands", country_code: "SB", currency_code: "SBD", time_zone: "" },
    { name: "Somalia", country_code: "SO", currency_code: "SOS", time_zone: "" },
    { name: "South Africa", country_code: "ZA", currency_code: "ZAR", time_zone: "" },
    { name: "South Georgia", country_code: "GS", currency_code: "SHP", time_zone: "" },
    { name: "South Korea", country_code: "KR", currency_code: "KRW", time_zone: "" },
    { name: "South Sudan", country_code: "SS", currency_code: "SSP", time_zone: "" },
    { name: "Spain", country_code: "ES", currency_code: "EUR", time_zone: "" },
    { name: "Sri Lanka", country_code: "LK", currency_code: "LKR", time_zone: "" },
    { name: "Sudan", country_code: "SD", currency_code: "SDG", time_zone: "" },
    { name: "Suriname", country_code: "SR", currency_code: "SRD", time_zone: "" },
    { name: "Svalbard and Jan Mayen", country_code: "SJ", currency_code: "NOK", time_zone: "" },
    { name: "Sweden", country_code: "SE", currency_code: "SEK", time_zone: "" },
    { name: "Switzerland", country_code: "CH", currency_code: "CHF", time_zone: "" },
    { name: "Syria", country_code: "SY", currency_code: "SYP", time_zone: "" },
    { name: "Taiwan", country_code: "TW", currency_code: "TWD", time_zone: "" },
    { name: "Tajikistan", country_code: "TJ", currency_code: "TJS", time_zone: "" },
    { name: "Tanzania", country_code: "TZ", currency_code: "TZS", time_zone: "" },
    { name: "Thailand", country_code: "TH", currency_code: "THB", time_zone: "" },
    { name: "Timor-Leste", country_code: "TL", currency_code: "USD", time_zone: "" },
    { name: "Togo", country_code: "TG", currency_code: "XOF", time_zone: "" },
    { name: "Tokelau", country_code: "TK", currency_code: "NZD", time_zone: "" },
    { name: "Tonga", country_code: "TO", currency_code: "TOP", time_zone: "" },
    { name: "Trinidad and Tobago", country_code: "TT", currency_code: "TTD", time_zone: "" },
    { name: "Tunisia", country_code: "TN", currency_code: "TND", time_zone: "" },
    { name: "Türkiye", country_code: "TR", currency_code: "TRY", time_zone: "" },
    { name: "Turkmenistan", country_code: "TM", currency_code: "TMT", time_zone: "" },
    { name: "Turks and Caicos Islands", country_code: "TC", currency_code: "USD", time_zone: "" },
    { name: "Tuvalu", country_code: "TV", currency_code: "AUD", time_zone: "" },
    { name: "Uganda", country_code: "UG", currency_code: "UGX", time_zone: "" },
    { name: "Ukraine", country_code: "UA", currency_code: "UAH", time_zone: "" },
    { name: "United Arab Emirates", country_code: "AE", currency_code: "AED", time_zone: "" },
    { name: "United Kingdom", country_code: "GB", currency_code: "GBP", time_zone: "" },
    { name: "United States", country_code: "US", currency_code: "USD", time_zone: "" },
    { name: "United States Minor Outlying Islands", country_code: "UM", currency_code: "USD", time_zone: "" },
    { name: "United States Virgin Islands", country_code: "VI", currency_code: "USD", time_zone: "" },
    { name: "Uruguay", country_code: "UY", currency_code: "UYU", time_zone: "" },
    { name: "Uzbekistan", country_code: "UZ", currency_code: "UZS", time_zone: "" },
    { name: "Vanuatu", country_code: "VU", currency_code: "VUV", time_zone: "" },
    { name: "Vatican City", country_code: "VA", currency_code: "EUR", time_zone: "" },
    { name: "Venezuela", country_code: "VE", currency_code: "VES", time_zone: "" },
    { name: "Vietnam", country_code: "VN", currency_code: "VND", time_zone: "" },
    { name: "Wallis and Futuna", country_code: "WF", currency_code: "XPF", time_zone: "" },
    { name: "Western Sahara", country_code: "EH", currency_code: "DZD", time_zone: "" },
    { name: "Yemen", country_code: "YE", currency_code: "YER", time_zone: "" },
    { name: "Zambia", country_code: "ZM", currency_code: "ZMW", time_zone: "" },
    { name: "Zimbabwe", country_code: "ZW", currency_code: "BWP", time_zone: "" },
];
